server.port: 9603
spring.application.name: service-consumer

spring.cloud.nacos.discovery.server-addr: 127.0.0.1:8848
feign.client.config.default.connectTimeout: 10000
feign.client.config.default.readTimeout: 10000
